### ISSUE TITLE
WindiCSS IntelliSense dont no support Autocomplete and more features

### ISSUE THREAD

**Issue by Scouterdev** [munxar/sveltekit-tailwind#4]
Installl WindiCSS IntelliSense for VS Code, does not display (Autocomplete) Intelligent suggestions for utilities and variants..

But deleting file tailwind.config.js all features starts working..
but in that case I will not have configuring Windi CSS file..

**Comment by munxar** [comment]
I started to use the way windicss is doing the config with a windi.config.ts file (https://windicss.org/guide/configuration.html)
I must confess that I have never overwritten utilities or variants in the config, so it's possible that the vs code plugin can't parse my suggested tailwind.config.js file.
do you have an example config file where the plugin stops to work?

**Comment by munxar** [comment]
@Klonuotas check out the latest main branch, I updated to a windi.config.ts file. seams to quiet my vs code windicss plugin.

**Comment by Scouterdev** [comment]
before that was **module.exports = { ]** for windi.config.js and change to **export default defineConfig({ })**

and fix problem for WindiCSS IntelliSense..

but have more problem for this code.

written code inside class  **{enabled ? 'opacity-0' : 'opacity-100'}**  does not display (Autocomplete) for  WindiCSS IntelliSense but remove this code, all everything working for CSS for a class name by hovering over it.

**E.g for code:**

```
export let enabled = false;
const toggle = () => (enabled = !enabled);
```
<span
   class="**{enabled
	? 'opacity-0'
	: 'opacity-100'}**  ease-in duration-200 absolute inset-0 h-full w-full flex items-center justify-center transition-opacity"
	aria-hidden="true"
>

or not allowed written code inside class for **{enabled ? 'opacity-0' : 'opacity-100'}**?

**Comment by munxar** [comment]
this is something you should ask in the windicss intellisense github repo. I think the intellisense can't know that you are in a class context. Imho this has nothing to do with the setup.
